### ISSUE TITLE
Additional Abbreviations

### ISSUE THREAD

**Issue by nickforrester1** [theodi/BDNS#111]
We have several items that are not currently listed, please see below items and suggested abbreviations:
Fan Coil Unit Artus - FCUA - Not currently listed. Suggestion to differentiate between regular and artus units.
Vacuum Degasser - Suggested reference is VCDG.
Buffer Vessel - Suggested reference is BFVSL using BF for buffer and VSL for vessel.
Door Curtain - Suggested reference is ODRH as an abbreviation for Over Door Heater. 
UV Filter - Suggested reference is UVFLT. Following other conventions combining UV and FLT for filter.
BV Filter - Suggested reference is BVFLT. Following other conventions combining BV and FLT for filter.
Carbon Filtration Unit - Suggested reference is CFU as an abbreviation of Carbon Filtration Unit.
Rainwater Pumpset - Suggested reference is RWP. Following other conventions combining RW for rainwater and P as used for pumps.
Indoor Air Quality Sensor -Suggested reference is IAQM as an abbreviation of Indoor Air Quality Monitoring.
Outdoor Air Quality Sensor - Suggested reference is OAQM as an abbreviation of Outdoor Air Quality Monitoring.
Fuel Fillpoint - Fuel Oil Pump if FOP so following this abbreviating from Fuel Oil Fill Point.
Request To Exit Proximity - Suggested reference is RTEP as an abbreviation of Request To Exit - Proximity.
Window Contacts - Suggested reference is WDC, where WD is confirmed for window and added C for contact.
Door Contact - Suggested reference is DRC, where DR is confirmed for door and added C for contact.
Maglocks - Suggested reference is DRC, where DR is confirmed for door and added ML for maglock.
Electronic Door Holder - Suggested reference is EDRH, using E for electronic, DR which is confirmed for door and added H for holder.
Server - SRVR - This will be relevant for any type of server located on site for all trades.

Thanks.

**Comment by RitaLav** [comment]
For UV, please use the abbreviation listed here: https://github.com/theodi/BDNS/issues/74
For UV, please use the abbreviation listed here: https://github.com/theodi/BDNS/issues/103
For rainwater, please refer to https://github.com/theodi/BDNS/issues/80

**Comment by nickforrester1** [comment]
@RitaLav an example of a maglock datasheet can be found [here](https://cdvi.co.uk/sites/cdviuk/files/manual/CDVI_V3%20Series_DS_02_EN_A4_C_1.pdf)

I will use the suggested references for contact sensor, UV and rainwater. Thanks.

**Comment by nickforrester1** [comment]
@pisuke
Understood regarding the Artus, can we suggest FCUP to indicate a packaged unit?
Will use MTS for all Air Quality Monitors.

**Comment by nickforrester1** [comment]
In discussions with Arup regarding the above references and have had some feedback from them also:
Overdoor Heater - Was suggested as ODRH but the item of plant is technically a Warm Air Curtain so suggested reference as WAC.
Carbon Filtration Unit - Was suggested as CFU, Arup are wanting to keep all filter items as FLT so suggested reference is CFLT.
Request To Exit Proximity -Was suggested as RTEP, Arup are wanting to use RETPR using PR to differentiate from P which is used for pumps.
Electronic Door Holder - Was suggested as EDRH, Arup want to use ELDRH allowing EL to differentiate from E which is used for extract.

**Comment by nickforrester1** [comment]
@RitaLav @pisuke do you have any further comments to the above? We are looking to move forward with instructing the contractors for their drawings and would like to get it right first time around if possible. Thanks.

**Comment by nickforrester1** [comment]
Hi @pisuke,

Thankyou for the responses. REgarind gthe queries I have answered them below:

Fan Coil Unit Artus - why not just using FCU? We have a mixture of units which are packed and regular. This was to differentiate the different operations of the units.
Request To Exit Proximity - Can you please provide a datasheet for this? Datasheet can be found for an example [here](https://norbain.com/wp-content/uploads/2018/10/EN_DA420-Data-sheet.pdf)
Vacuum Degasser - we have DGA: filter - degasser filter. Is this the same or a different thing? It appears that they are so happy to use the reference for degasser filter.
Buffer Vessel - isn't this a thermal storage or water tank? It is commonly in place to remove short cycling in closed water systems. Happy to use any suggestion but we already have specific water tanks which will have different parameters.
BV Filter - Is this a bacterial viral filter? I believe this is correct.
Fuel Fillpoint - Can you please provide a datasheet for this? Datasheet an be found [here](https://www.mwatechnology.com/wp-content/uploads/2015/08/400016XX-Fill-Valve-Assemblies.pdf). This is essentially a manual valve for oil filling.

Thanks.

**Comment by jgunstone** [comment]
i think this has moved on since the last comment - I've summarised the remaining items and suggestions below: 

- [x] Indoor Air Quality Sensor - please use MTS (existing)
- [x] Outdoor Air Quality Sensor - please use MTS (existing)
- [x] UV Filter - please use UVDU (uv disinfection unit, existing)
- [x] Rainwater Pumpset - please use RNWP (rain water pump, existing)
- [x] Door Contact - please use CNTS (contact sensor, existing)
- [x] Window Contacts - please use CNTS (contact sensor, existing)
- [x] Server - please use DPU or SRV (data processing unit / computer, existing)
- [ ] Overdoor Heater or Door Curtain - please use WAC (warm air curtain, to be added)
- [ ] Carbon Filtration Unit - please use CFLT (carbon filter, to be added)
- [ ] Electronic Door Holder - please use EMDH (electromagnetic door holder, to be added)
- [ ] Maglocks - please use MLOCK (magnetic lock, to be added).


Some more questions/thoughts

- [x] Fan Coil Unit Artus - suggest FCU. references to manufacturers is avoided in BDNS
- [ ] Request To Exit Proximity - Can you please provide a datasheet for this?
- [x] Vacuum Degasser - suggest using DGA
- [x] Buffer Vessel - many options available. search TANK in [BDNS_Abbreviations_Register](https://github.com/theodi/BDNS/blob/master/BDNS_Abbreviations_Register.csv)
- [ ] BV Filter - Is this a bacterial viral filter?
- [ ] Fuel Fillpoint - Can you please provide a datasheet for this?

**Comment by RitaLav** [comment]
Added the below:

Carbon Filtration Unit - please use CFLT (carbon filter, to be added)
Electronic Door Holder - please use EMDH (electromagnetic door holder, to be added)
Maglocks - please use MLOCK (magnetic lock, to be added)

Closing the issue for now. If needed, please go ahead and reopen it.
