### ISSUE TITLE
Additional Asset Requests

### ISSUE THREAD

**Issue by JimGriffin88** [theodi/BDNS#117]
Hi, looking to resolve the following assets:

Description: Combined Heat and Power Unit
Suggested Abbreviation: CHP
Example: https://www.viessmann.co.uk/products/combined-heat-and-power/large-scale-chp-boilers#:~:text=Combined%20heat%20and%20power%20units,in%20parallel%20to%20a%20boiler.

Description: Gas Solenoid Valve, used to isolate a gas line, commonly features as a safety device.
Suggested Abbreviation: GSNV
Example: https://www.flamefast-gas-safety.co.uk/gas-solenoid-valves.html

In addition to the above can you advise if the following abbreviation is approved as per issue #99  : 

Differential Pressure Switch - DPRSW

**Comment by jgunstone** [comment]
CHP has been added 
![image](https://user-images.githubusercontent.com/21370980/231503075-a1de05fc-3a22-4081-8d65-e809c68c1807.png)

so has DPRSW: 
![image](https://user-images.githubusercontent.com/21370980/231503369-3a1d191d-7ead-4062-a844-98afb739e04e.png)

GSNV hasn't
suggest that this issue is closed as complete and a separate issue is created GSNV if required

**Comment by RitaLav** [comment]
In addition to the comments above, 'solenoid valve' exists in the abbreviation list as 'SNV'. 

If an abbreviation is required specifically for gas (and the generic one for solenoid doesn't work) could you please let us know?
