### ISSUE TITLE
Smoke Control Damper- SCD

### ISSUE THREAD

**Issue by s-buchan** [theodi/BDNS#149]
**Smoke Control Damper**
Damper for controlling the flow of smoke as part of a smoke control system. Does not have a failsafe position unlike a Fire Damper.  Product standard EN 12101-8.
![mandiksedml](https://user-images.githubusercontent.com/63742889/213431343-09c36828-4338-4b91-ba03-44562890d249.png)

**SCD**
While there are several existing abbreviations for dampers in the register, none of them are explicitly for Smoke Control Dampers. The existing term 'Smoke Damper- SD' could be understood to refer to either a Fire Damper with a smoke leakage (S) classification, or a Smoke Control Damper.  
It is important to avoid confusion between Fire Dampers tested to BS EN 1366-2 only, and Smoke Control Dampers which are also tested to BS EN 1366-10. These are different products that serve different functions, regulated by two separate product standards. A Fire Damper closes in the event in a fire to maintain compartmentation. A smoke control damper will open or close depending on the location of the fire to allow smoke to be extracted from the fire compartment whilst maintaining overall compartmentation. 
When a fire damper has been installed where a smoke control damper is required or vice versa, it is a life safety issue. Clear terminology separating the two is required.

**device/asset documentation**
Example Datasheet : [Mandik SEDM-L](https://www.mandik.com/getattachment/ce5979eb-1d9f-438a-a3c4-4d7abc569854/146_20_en_SEDM-L.aspx)

The term Smoke Control Damper is common parlance and used in industry guidance including:
- Approved Document B Volume 1
- Smoke Control Association Guidance on smoke control to common escape routes in apartment buildings (flats and maisonettes).
- CIBSE Guide E Fire Safety Engineering
- Product Standard EN 12101-8

**Comment by SKing-93** [comment]
Thanks, currently we have:

damper - motorised fire smoke damper - MFSD
damper - motorised smoke damper - MSD 

Does this provide sufficient distinction to cover your points of the regulatory and functional differences?

**Comment by s-buchan** [comment]
Hi, Thanks very much for reviewing my request.

I think similar to 'smoke damper' the terms 'motorised fire smoke damper' and 'motorised smoke damper' are potentially ambiguous. They are often used to refer to fail-safe fire dampers (tested to BS EN 1366-2 only) and so aren't clear enough for referring to a Smoke Control Damper (tested to BS EN 1366-10).

It's important that we have really clear definitions in building fire terminology and there's a lot of scrutiny required for life safety systems. This is something we've been tightening up in all of our own standard templates etc. so it would be great if we could maintain this distinction in BDNS

**Comment by jgunstone** [comment]
would be good to close this issue out... 
just reviewed this with @s-buchan  and the Max Fordham mechanical group.

to reiterate/summarise @s-buchan points: 
2 types of dampers defined by standards above
- Fire Dampers (includes fire and smoke types) - close to maintain fire compartmentalisation
- Smoke Control Dampers - always motorised. will either open or close depending on location to control safe removal of smoke.

in BDNS:
FD - damper - fire damper --> _Fire Damper_
MFSD - damper - motorised fire smoke damper --> _Fire Damper_
MSD - damper - motorised smoke damper --> _Fire Damper_
BYCD - damper - bypass control damper _(not typically for fire and smoke ?)_


so currently missing from the database is an abbreviation for a device that is explicitly for smoke control, rather than compartmentalisation. This is important because there function in the event of fire is very different, so for engineers reading a drawing it should be clear what type of device is being referred to to allow for successful review of the strategy.

MSD has been historically used but this leads to confusion as it can be used either as a _Fire Damper_ or as a _Smoke Control Damper_. Hence the request for an additional term. 

MSCD would also work, as smoke control dampers are always motorised.

**Comment by RitaLav** [comment]
As per meeting on April 19th, MSCD to be added to the abbreviation register.

**Comment by RitaLav** [comment]
Addressed in pull request #156
