### ISSUE TITLE
Cable Management

### ISSUE THREAD

**Issue by kieronmmoore** [theodi/BDNS#172]
Device/asset description
The devices required for cable management of cables within building. This cover the organisation, protection and routing of wiring and cables within a building. The suggested abbreviations start with CA to show they are all part of the cable management system. 

device/asset name

| Asset Name  | Asset Abbreviation | dbo_entity_type | ifc_class  | ifc_type | asset example |
| ------------- | ------------- | ------------- | ------------- | ------------- |------------- |
| Cable management - Cable Basket | CABASK  |  | IfcCableCarrierSegmentType | NOTDEFINED | www.pgrahame.com/catalogue/basket-tray.html?v=215|
| Cable management - Cable Ladder   | CALAD  |  | IfcCableCarrierSegmentType | CABLELADDERSEGMENT | www.pgrahame.com/catalogue/cable-ladder.html?v=215 |
| Cable management - Cable Tray   | CATR  | | IfcCableCarrierSegmentType | CABLETRAYSEGMENT | www.pgrahame.com/catalogue/books/pdf/3_Cable_Tray.pdf?v=215 |
| Cable management - Cable Trunking  | CATRNK  | | IfcCableCarrierSegmentType | CABLETRUNKINGSEGMENT | www.pgrahame.com/catalogue/standard-trunking.html?v=215 |
| Cable management - Floor Trunking   | CAFTRNK  | | IfcCableCarrierSegmentType | NOTDEFINED | https://storage.electrika.com/flips/0600-floor-perimeter-systems-22/index.html#page=44 |

**Comment by kieronmmoore** [comment]
I agree with the suggestion to change the abbreviation for Cable management - Floor Trunking from CAFTRNK in my orignal comment to CAFTRK

**Comment by RitaLav** [comment]
A high level comment from Arup side after an internal discussion is whether these abbreviations are strictly needed to be included as part of BDNS, or whether it would be sufficient for designers to come up with an abbreviation and full asset name that follows BDNS principles?

**Comment by jgunstone** [comment]
hi @RitaLav  - 
its a fair point - I think cable management is probably lower on the priorities as something that BDNS needs to track. 

generally, if equipment needs tagging on a drawing it requires an abbreviation. Cable management equipment is probably more likely to be specified globally for the project within a Specification rather than referred to on a drawing, so in this way it may not be required.

My use case is that I'm using the abbreviation as an index key for a database of specification data. (that is a use case noted here: https://github.com/theodi/BDNS#use). It is possible that these abbreviations don't actually appear in output information, as we might just say that all, for example, cable baskets of category https://uniclass.thenbs.com/taxon/pr_65_70_11_12 must be to this spec... rather than having a schedule of all the different cable basket products and cross-referencing that to drawings....
