### ISSUE TITLE
Additional Bluetooth Equipment 

### ISSUE THREAD

**Issue by Snledge** [theodi/BDNS#257]
Requesting to add Bluetooth devices to the BDNS Abbreviations;

Bluetooth Beacon System Gateway - BLGW
Bluetooth Management System - BLMS
Bluetooth Beacons - BLBC

Datasheets;
[APN0013 Rev 1.1 - Making Sense of Bluetooth Beacon Data.pdf](https://github.com/user-attachments/files/16066898/APN0013.Rev.1.1.-.Making.Sense.of.Bluetooth.Beacon.Data.pdf)
[DS_LocationServices.pdf](https://github.com/user-attachments/files/16066899/DS_LocationServices.pdf)

**Comment by RitaLav** [comment]
The following will be added:

Bluetooth Beacons - BTB

On gateway: Could you please provide a datasheet? If it is a generic comms gateway, could you use the existing abbreviation 'CGW'

On Management system: could you provide a datasheet please so that we can better understand it? 

Note for completeness: we will also update the following from:
av equipment - bluetooth audio interface | BAI

to: BTAI
