### ISSUE TITLE
Fire Alarm Switch Monitor

### ISSUE THREAD

**Issue by Snoreledge** [theodi/BDNS#43]
We will need an abbreviation for this Intelligent Switch Monitor Unit for the fire alarm systems. Could we please provide an update. 
[20004900_0001.pdf](https://github.com/theodi/BDNS/files/5920295/20004900_0001.pdf)

**Comment by adam4521** [comment]
Proposed entries to BDNS (snip from .csv file):

fire - break glass unit,BGU,IfcAlarm,BREAKGLASSBUTTON
fire - smoke detector,SD,IfcSensor,SMOKESENSOR
fire - heat detector,HD,IfcSensor,HEATSENSOR
fire - gas detector,GD,IfcSensor,GASSENSOR
fire - aspirating smoke detector,ASD,,
fire - input output interface unit,IFU,,
fire - alarm annunciator sounder or beacon,FAS,,
fire - control and indication equipment,CIE,,
fire suppression - sprinkler head,SPH,IfcFireSuppressionTerminal,SPRINKLER
fire suppression - sprinkler flow switch,FS,,
fire suppression - sprinkler isolation valve,ISV,,
fire suppression - fire jockey pump,FJP,,
fire suppression - fire pump,FP,,
fire suppression - fire pump control panel,FPCP,,
fire suppression - sprinkler alarm bell,FB,,
fire suppression - gas suppression control panel,GSCP,,
fire suppression - gas suppression head,GSH,,

The smoke detector/sensor is already in the sensor section but I propose that fire alarm devices and fire suppression devices are distinct blocks that are separate from non-emergency sensors --- this is because the design code requirements are so specific, fire sensors can't be considered as part of a more general building sensor system. I'm having some trouble searching the IFC documents, so it is possible some more of these elements have definitions there.

**Comment by KenEnright** [comment]
@Snoreledge - As noted on Aconex, IFU is this case.

**Comment by KenEnright** [comment]
@adam4521 Thanks for posting the proposals. For the associated industry foundation class and enumeration, would this be the closest? http://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifccommunicationsappliancetypeenum.htm

**Comment by pisuke** [comment]
I've created PR #95 to reorganise the fire related abbreviations.
Thank you @Snoreledge for the useful suggestions!
