### ISSUE TITLE
Add Sound Level Sensor

### ISSUE THREAD

**Issue by vsigno** [theodi/BDNS#64]
Suggest as _SLS (Sound Level Sensor)_ within the ifc_class _IfcSensor_. It may be less common than other sensors but I could not find any alternative name in the existing list

sensor - sound level sensor,SLS,IfcSensor,SOUNDLEVELSENSOR

**Comment by RitaLav** [comment]
Agree with suggested abbreviation 'SLS'

**Comment by RitaLav** [comment]
Still looks ok in further weekly meeting review. @pisuke can we add?

**Comment by TheFridgeShaman** [comment]
After checking the IfcSensorTypeEnum for [IFC4 4.0.2.1](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/ifcbuildingcontrolsdomain/lexical/ifcsensortypeenum.htm)  and [IFC4.3.dev](http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcSensorTypeEnum.htm), please note that the available type value for the IfcSensorTypeEnum would be SOUNDSENSOR, instead of SOUNDLEVELSENSOR.

**Comment by RitaLav** [comment]
Pull request submitted and abbreviation added to register
