### ISSUE TITLE
Additional HVAC items

### ISSUE THREAD

**Issue by john-c-OSS** [theodi/BDNS#99]
Differential pressure switch – suggesting DPSW as DPS has already been used for Differential Pressure Sensor.

Boiler Module – BLR is used for Boiler but some particular boilers we are working on consist of three boiler modules - so we suggest BLRM

**Comment by john-c-OSS** [comment]
Also, another couple of assets required for door curtain heaters:

Suggest **dch**, then for a door curtain chilled **dcc**

**Comment by RitaLav** [comment]
From weekly sync, the request for Differential pressure switch seems reasonable, however the abbreviation is reserved for:

"actuator - dew point switch | DPSW".

Would DPRS work instead? @pisuke @richardkreid thoughts?

**Comment by RitaLav** [comment]
Boiler module - are the modules external to the boiler?

**Comment by RitaLav** [comment]
From weekly sync - dch and dcc make sense

**Comment by pisuke** [comment]
My main comment is about the boiler, it is more like a modular boiler rather than a boiler module. So I would still call it a boiler.

The differential pressure switches are effectively also sensors, just outputting binary instead of analogue/continuous values.

@richardkreid do you have any comments?
